In [1]:
import numpy as np

In [2]:
a= np.random.randint(1,100,15)
a

array([42, 39, 25, 28, 51, 14, 31, 11, 17, 69,  6, 40, 31, 36, 25],
      dtype=int32)

In [ ]:
a.shape # showing 1D array

(15,)

In [ ]:
#FOR AXIS=0

In [8]:
# convert 1 D array into 2 D
p = np.expand_dims(a,axis=0)
p

array([[42, 39, 25, 28, 51, 14, 31, 11, 17, 69,  6, 40, 31, 36, 25]],
      dtype=int32)

In [ ]:
#after using this above function shape is be like which is 2D
p.shape

(1, 15)

In [ ]:
#FOR AXIS=1

In [10]:
q = np.expand_dims(a,axis=1)
q

array([[42],
       [39],
       [25],
       [28],
       [51],
       [14],
       [31],
       [11],
       [17],
       [69],
       [ 6],
       [40],
       [31],
       [36],
       [25]], dtype=int32)

In [15]:
# again you can convert 2D array 3d
import numpy as np

a = np.arange(6).reshape(2, 3)   # 2D array
print("Print a:\n")
print(a)
print("shape of a:\n",a.shape)

# Add a new axis (convert to 3D)
b = np.expand_dims(a, axis=2)
print("Print b:\n")
print(b)
print("shape of b:\n",b.shape)


Print a:

[[0 1 2]
 [3 4 5]]
shape of a:
 (2, 3)
Print b:

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
shape of b:
 (2, 3, 1)
