In [ ]:
# Working with Mathematical Formula

In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
# Sigmoid Function 
# (uses in ML and DL mostly in Logestic function)

In [7]:
def sigmoid(array):
    return 1/(1+np.exp(-(array)))

a= np.arange(10)
sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [ ]:
#So i the above example of sgmoid we can see all the numbers are between 0 and 1

In [ ]:
# mean squared error

In [8]:
#(create two array)
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

In [ ]:
#categorical cross entropy

In [9]:
actual

array([35,  6,  3, 36, 39,  6, 36,  8, 17, 36, 31, 25, 47, 41, 30,  6, 27,
       32, 31, 11, 22,  6,  2, 17, 35], dtype=int32)

In [10]:
predicted

array([45, 13, 38, 43, 48,  1, 22,  3, 34, 15, 48,  2, 26,  4,  9, 40, 49,
       17, 41, 43, 22, 42, 27, 48, 25], dtype=int32)

In [ ]:
def mse(actual,predicted):
    return np.mean((actual-predicted)**2)
print(mse(actual,predicted))#linear regression is mse

460.8


In [ ]:
# categorical cross entropy
np.mean((actual-predicted)**2)

array([ 100,   49, 1225,   49,   81,   25,  196,   25,  289,  441,  289,
        529,  441, 1369,  441, 1156,  484,  225,  100, 1024,    0, 1296,
        625,  961,  100], dtype=int32)

In [ ]:
#Binary Cross Entropy (BCE)
#Binary Cross Entropy is a loss function used mainly for binary classification problems (output = 0 or 1).

# BCE=−[ylog(p)+(1−y)log(1−p)]

In [ ]:
y = np.array([1, 0, 1])
p = np.array([0.9, 0.2, 0.8])

bce = -np.mean(y*np.log(p) + (1-y)*np.log(1-p))
print(bce)#logistic regrestion is bce

0.18388253942874858


In [ ]:
# Working with missing value -> np.nan
a = np.array([1,2,3,4,np.nan,6])
a

array([ 1.,  2.,  3.,  4., nan,  6.])