In [1]:
import numpy as np

In [2]:
# Working with missing value -> np.nan
a = np.array([1,2,3,4,np.nan,6])
a

array([ 1.,  2.,  3.,  4., nan,  6.])

In [ ]:
# doing boolean indexing to find out the missing value
np.isnan(a)

array([False, False, False, False,  True, False])

In [5]:
#to get that missing value which is returning true
a[np.isnan(a)]

array([nan])

In [6]:
#to get all non missing value just add a "NOT OPERATOR"
a[~np.isnan(a)]

array([1., 2., 3., 4., 6.])