In [ ]:
import numpy as np #pip install numpy


In [19]:
a1 = np.random.random((3,3))
# Range of values
# → Each number is ≥ 0.0 and < 1.0

In [16]:
print(a1)

[[0.15206639 0.28128601 0.99728375]
 [0.55771513 0.1971494  0.32392075]
 [0.09592451 0.36227659 0.31300242]]


In [17]:
a1 = np.round(a1*100)

In [18]:
print(a1)

[[ 15.  28. 100.]
 [ 56.  20.  32.]
 [ 10.  36.  31.]]


In [28]:
# Aggregation / Reduction functions

In [ ]:
#max OR #sum OR #product

In [11]:
np.max(a1,axis=1)#now find the maximumm element in each row 


array([75., 85., 78.])

In [27]:
np.sum(a1, axis=0)  # column-wise
np.sum(a1, axis=1)  # row-wise

array([1.77569439, 1.29780942, 1.08345023])

In [13]:
np.prod(a1,axis=1)#now find the prod element in each row 

array([147900.,  41820.,  45630.])

In [ ]:
#mean / median /std / var

In [ ]:
np.mean(a1) #mean

np.float64(52.888888888888886)

In [ ]:
np.std(a1,axis=1)#It calculates the standard deviation of each row in the array a1.

array([0.12792683, 0.26136891, 0.14528272])

In [ ]:
np.median(a1,axis=1)#median

array([0.52745243, 0.5026439 , 0.3100224 ])

In [23]:
np.std(a1,axis=1)#median

array([0.12792683, 0.26136891, 0.14528272])

In [24]:
np.var(a1,axis=1)#vairance

array([0.01636527, 0.06831371, 0.02110707])

In [29]:
#Trigonometric Function

In [ ]:
np.sin(a1)#sin theta

array([[0.50333364, 0.45975645, 0.69650919],
       [0.4817441 , 0.65326861, 0.08317576],
       [0.21273856, 0.53038192, 0.30507997]])

In [31]:
np.cos(a1)#cos theta

array([[0.86409215, 0.88804505, 0.71754787],
       [0.87631194, 0.75712623, 0.99653489],
       [0.97710916, 0.84775882, 0.95232674]])

In [32]:
np.tan(a1)#tan theta

array([[0.58249996, 0.51771749, 0.97067976],
       [0.54974043, 0.86282654, 0.08346497],
       [0.21772241, 0.62562831, 0.3203522 ]])

In [ ]:
#DOT PRODUCT OF TWO MATRIX such (a X b) . (b X c)
# important  criteria for dot product among the two matrix col of previous matrix must matches with row of the second matrix

a2 = np.arange(12).reshape(3,4)# Matrix 1
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3 = np.arange(12,24).reshape(4,3)#Matrix 2
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [37]:
# Matrix 1 dot Matrix 2
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#log and exponents

In [ ]:
np.log(a1)#log

array([[-0.6396966 , -0.73872855, -0.26068834],
       [-0.68787331, -0.33982687, -2.4856434 ],
       [-1.54001993, -0.58151456, -1.17111073]])

In [39]:
np.exp(a1)#exponent

array([[1.69460967, 1.61239545, 2.16089184],
       [1.6530861 , 2.03784639, 1.08683734],
       [1.23908949, 1.74901191, 1.36345565]])

In [ ]:
#round / floor / ceil

In [41]:
result = np.random.random((2,3))*100 # 2 X 3 Matrix
result

array([[59.70806008, 24.21950308, 43.63247605],
       [79.8822316 , 30.84794506, 85.02841756]])

In [42]:
np.round(result)# Round to nearest integer


array([[60., 24., 44.],
       [80., 31., 85.]])

In [43]:
#smallest integer >= value
np.ceil(result)

array([[60., 25., 44.],
       [80., 31., 86.]])

In [44]:
# Floor: largest integer <= value
np.floor(result)

array([[59., 24., 43.],
       [79., 30., 85.]])