In [1]:
import numpy as np


In [2]:
# Array Operation
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)


In [3]:
print(a2)


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [4]:
#Scaler Operation
print(a1 ** a2)


[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]]


In [5]:

#relational operator
print(a2>5)


[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [6]:
#vector operator
print(a1+a2) # as both of thenm as same shape so add them item wise


[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [7]:
#similarly
print(a1**a2)

[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]]
