In [1]:
#np.array
import numpy as np

In [2]:
# 1D numpy array (vector)
print("1d array:")
a=np.array([1,2,3])#inside np.arry include a list.
print(a)
print(type(a))#type 


1d array:
[1 2 3]
<class 'numpy.ndarray'>


In [3]:
# 2D numpy array (matrix)
print("2d array:")
b= np.array([[1,2,3],[4,5,6]])#you can also call it matrix
print(b)


2d array:
[[1 2 3]
 [4 5 6]]


In [4]:
#3D numpy array (tensor)
print("3d array:")
c = np.array([[[1,2],[1,3]],[[5,6],[7,8]]])
print(c)


3d array:
[[[1 2]
  [1 3]]

 [[5 6]
  [7 8]]]


In [5]:
#data type
print("Data Type: Float")
d= np.array([1,2,3],dtype=float)
print(d)


Data Type: Float
[1. 2. 3.]


In [6]:
print("Data Type: Boolean")
e= np.array([1,0,3],dtype=bool)#for 0 it gives false
print(e)


Data Type: Boolean
[ True False  True]


In [7]:
print("Data Type:Complex Number")
f = np.array([1,0,7],dtype=complex)
print(f)


Data Type:Complex Number
[1.+0.j 0.+0.j 7.+0.j]


In [8]:
print("Data Type:Float Number")
g = np.array([1,0,7],dtype=float)
print(g)


Data Type:Float Number
[1. 0. 7.]
