In [1]:
import numpy as np

In [ ]:
a1 = np.arange(12)#1D
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a2 = np.arange(12).reshape(4,3)#2D
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
a3 = np.arange(27).reshape(3,3,3)#3D
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
#Loop in 1D array
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
#Loop in 2D array
for i in a2:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [10]:
#Loop in 3D array
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):# iterating only the elements
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
