In [1]:
import numpy as np

In [ ]:
#Reshaping consisted of 3 things:
# 1.Reshape
# 2.Transpose
# 3.Ravel

In [2]:
a1 = np.arange(10)#Array 1
a2 = np.arange(12).reshape(3,4)#Array 2
a3 = np.arange(8).reshape(2,2,2)#Array 3

In [ ]:
#reshape


In [ ]:
#transpose
np.transpose(a2)
# Easy syntax 
# a2.T(Tranpose)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
#ravel
# It can convert any dimentional array to 1D
print("Initialy:")
print(a2)
print("After raveling:")
a2.ravel()

Initialy
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After raveling


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
print("Initialy:")
print(a3)
print("After raveling:")
a3.ravel()

Initialy:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
After raveling:


array([0, 1, 2, 3, 4, 5, 6, 7])