In [ ]:
#np.sort

In [1]:
import numpy as np
a= np.random.randint(1,100,15)
a

array([60, 41, 12, 13, 36, 37, 45,  6, 82, 26, 12, 48, 65, 90, 44],
      dtype=int32)

In [3]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[33, 42, 53, 71],
       [71, 53, 26, 59],
       [19, 85, 68, 29],
       [15, 73,  2, 20],
       [68, 67, 28, 62],
       [10, 14, 27, 21]], dtype=int32)

In [5]:
np.sort(a)

array([ 6, 12, 12, 13, 26, 36, 37, 41, 44, 45, 48, 60, 65, 82, 90],
      dtype=int32)

In [11]:
np.sort(b,axis=1)#sort row wise

array([[33, 42, 53, 71],
       [26, 53, 59, 71],
       [19, 29, 68, 85],
       [ 2, 15, 20, 73],
       [28, 62, 67, 68],
       [10, 14, 21, 27]], dtype=int32)

In [10]:
np.sort(b,axis=0)#sort column wise

array([[10, 14,  2, 20],
       [15, 42, 26, 21],
       [19, 53, 27, 29],
       [33, 67, 28, 59],
       [68, 73, 53, 62],
       [71, 85, 68, 71]], dtype=int32)

In [13]:
np.sort(np.sort(b, axis=1), axis=0)#sort for row and column

array([[ 2, 14, 20, 27],
       [10, 15, 21, 68],
       [19, 29, 53, 71],
       [26, 42, 59, 71],
       [28, 53, 67, 73],
       [33, 62, 68, 85]], dtype=int32)

In [ ]:
np.sort(a)[::-1]#sorting in descending order

array([90, 82, 65, 60, 48, 45, 44, 41, 37, 36, 26, 13, 12, 12,  6],
      dtype=int32)