In [1]:
import numpy as np

In [12]:
import numpy as np

c = np.arange(6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)

print("c:\n", c)
print("d:\n", d)


c:
 [[0 1 2]
 [3 4 5]]
d:
 [[ 6  7  8]
 [ 9 10 11]]


In [8]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])