In [1]:
import numpy as np

In [2]:
a= np.random.randint(1,100,15)
a

array([41, 37, 56, 60, 91, 29, 77, 56, 47, 86, 46, 33, 80, 61,  6],
      dtype=int32)

In [3]:
#find the index position of the array where it is greater than 50
np.where(a>50)

(array([ 2,  3,  4,  6,  7,  9, 12, 13]),)

In [4]:
#replace all value >50 with 0
# np.where(condition,true,false)
np.where(a>50,0,a)#replace it with 0

array([41, 37,  0,  0,  0, 29,  0,  0, 47,  0, 46, 33,  0,  0,  6],
      dtype=int32)

In [6]:
# Replace all even numbers with 0
np.where(a%2==0,0,a)

array([41, 37,  0,  0, 91, 29, 77,  0, 47,  0,  0, 33,  0, 61,  0],
      dtype=int32)