In [2]:
import numpy as np

In [3]:
#Indexing and Slicing

In [4]:
#Make 3 array

In [5]:
a1 = np.arange(10)#Array 1
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a2 = np.arange(12).reshape(3,4)#Array 2
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a3 = np.arange(8).reshape(2,2,2)#Array 3
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
print(a1[-1])#last item of a1 

9


In [9]:
print(a1[0])#first item of a1

0


In [10]:
#To find the target element in a2
print(a2)
print(a2[1,2]) #location of 6 is at a2[1,2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6


In [13]:
print(a2[2,3])


11


In [14]:
#3D Matrix
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
print(a3[1,0,1]) #a3[layer][row][column] -> 2 layer 2 rows 3 colums
print(a3[0,1,0])

5
2


In [ ]:
#So through indexing we can fetch only one element at a time 

In [18]:
# Slicing (We can fetch multiple element from and to )

# in 1D array
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5]#between 2 and 5 index

array([2, 3, 4])

In [20]:
a1[2:5:2]#we can add alternate element too

array([2, 4])

In [ ]:
# For 2D array Slicing

In [23]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
a2[0,:]

array([0, 1, 2, 3])

In [25]:
a2[:,2]

array([ 2,  6, 10])

In [22]:
a2[1:,1:3]# 1 onwards and 1 onwards 3

array([[ 5,  6],
       [ 9, 10]])

In [26]:
#rows in alternate way
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2,1::2]#::row 1 and 2 selected  and 1 :: 2 means alternative elements are selected

array([[ 1,  3],
       [ 9, 11]])

In [29]:
a2[1,0::3]

array([4, 7])

In [ ]:
a2[0:2]#Step1 how many rows u required

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
#3D Array

In [49]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [51]:
#Find the second array
a3[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [52]:
# find 1st and Second array
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [61]:
#print the second rows of the first 2d array
a3[0,1,:]

array([3, 4, 5])

In [ ]:
#print middle colums of the second 2d matrix
a3[1,:,1]

array([10, 13, 16])

In [66]:
#print all the rows and columns from 1 onwards all
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
# Question : print [0,2] and [18,20]
#Step:1
a3[0::2] #Select the matrix on which u want to perform the operation

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#Step:2
a3[0::2,:1]#select 1st row from bothe the matrix

array([[[ 0,  1,  2]],

       [[18, 19, 20]]])

In [92]:
a3[0::2,:1,::2] #Select the element u want to choose from the first row
#a2(matrix,row,elements)

array([[[ 0,  2]],

       [[18, 20]]])