In [1]:
import numpy as np
a= np.random.randint(1,100,15)
a

array([98, 74, 69,  2, 48,  2, 99, 25, 51, 13, 30,  4,  1,  5, 89],
      dtype=int32)

In [2]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[34, 47, 76, 12],
       [73,  8, 38, 88],
       [44,  7, 67, 97],
       [ 5, 48, 99, 46],
       [39, 25, 73, 20],
       [33, 23, 43, 47]], dtype=int32)

In [3]:
#np.append

In [4]:
# It basically append the values along the mentioned axis at the end of the array 

In [5]:
a

array([98, 74, 69,  2, 48,  2, 99, 25, 51, 13, 30,  4,  1,  5, 89],
      dtype=int32)

In [6]:
np.append(a,200) # ifv u want to insert or append 200

array([ 98,  74,  69,   2,  48,   2,  99,  25,  51,  13,  30,   4,   1,
         5,  89, 200])

In [7]:
np.append(b,np.ones((b.shape[0],1)))# append 1 at the row all

array([34., 47., 76., 12., 73.,  8., 38., 88., 44.,  7., 67., 97.,  5.,
       48., 99., 46., 39., 25., 73., 20., 33., 23., 43., 47.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [8]:
np.append(b,np.ones((b.shape[0],1)),axis=1)# append 1 at the column all

array([[34., 47., 76., 12.,  1.],
       [73.,  8., 38., 88.,  1.],
       [44.,  7., 67., 97.,  1.],
       [ 5., 48., 99., 46.,  1.],
       [39., 25., 73., 20.,  1.],
       [33., 23., 43., 47.,  1.]])