In [3]:
import numpy as np
a= np.random.randint(1,100,15)
a

array([47, 54, 51, 79, 63,  8, 98, 61, 14, 18, 63, 53, 41, 98, 44],
      dtype=int32)

In [5]:
np.delete(a,0) # give index value

array([54, 51, 79, 63,  8, 98, 61, 14, 18, 63, 53, 41, 98, 44],
      dtype=int32)

In [6]:
np.delete(a,6)

array([47, 54, 51, 79, 63,  8, 61, 14, 18, 63, 53, 41, 98, 44],
      dtype=int32)

In [7]:
np.delete(a,[0,2,4])

array([54, 79,  8, 98, 61, 14, 18, 63, 53, 41, 98, 44], dtype=int32)