In [1]:
import numpy as np

In [ ]:
#np.cumsum - To compute the cumulative sum of an array on a given axis.

In [2]:
a= np.random.randint(1,100,15)
a

array([49, 18, 82,  9, 23, 36, 68, 80, 29, 32,  4, 16, 89,  1, 46],
      dtype=int32)

In [3]:
np.cumsum(a)

array([ 49,  67, 149, 158, 181, 217, 285, 365, 394, 426, 430, 446, 535,
       536, 582])

In [4]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[71, 21, 48, 31],
       [21, 88, 57,  5],
       [ 8,  1, 63, 44],
       [28, 63, 88, 10],
       [ 6, 97, 59, 72],
       [47, 60, 34, 18]], dtype=int32)

In [5]:
np.cumsum(b)

array([  71,   92,  140,  171,  192,  280,  337,  342,  350,  351,  414,
        458,  486,  549,  637,  647,  653,  750,  809,  881,  928,  988,
       1022, 1040])

In [ ]:
np.cumsum(b,axis=0)#on a particular axis =0 for column wise

array([[ 71,  21,  48,  31],
       [ 92, 109, 105,  36],
       [100, 110, 168,  80],
       [128, 173, 256,  90],
       [134, 270, 315, 162],
       [181, 330, 349, 180]])

In [8]:
np.cumsum(b,axis=1)#on a particular axis =0 for row wise

array([[ 71,  92, 140, 171],
       [ 21, 109, 166, 171],
       [  8,   9,  72, 116],
       [ 28,  91, 179, 189],
       [  6, 103, 162, 234],
       [ 47, 107, 141, 159]])

In [7]:
np.cumsum(b)

array([  71,   92,  140,  171,  192,  280,  337,  342,  350,  351,  414,
        458,  486,  549,  637,  647,  653,  750,  809,  881,  928,  988,
       1022, 1040])

In [9]:
# np.cumprod
np.cumprod(a)

array([                  49,                  882,                72324,
                     650916,             14971068,            538958448,
                36649174464,        2931933957120,       85026084756480,
           2720834712207360,    10883338848829440,   174133421581271040,
       -2948869552976429056, -2948869552976429056, -6520790920948875264])

In [10]:
a

array([49, 18, 82,  9, 23, 36, 68, 80, 29, 32,  4, 16, 89,  1, 46],
      dtype=int32)