In [ ]:
#Broadcasting
#The term boardcasting describes how Numpy treats arrays with different shapes during arithmetic operations,The smaller array is "broadcast" accross the large array so that they have compatible shapes.

In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [3]:
# diif shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [11]:
# Broadcasting Rules

# 1. Make the two arrays have the same number of dimensions.

# If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.

# 2. Make each dimension of the two arrays the same size.

# If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.

# If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

In [ ]:
# Example 1

In [14]:
import numpy as np

a = np.arange(3).reshape(1, 3)
b = np.arange(3).reshape(3, 1)

print("a:\n", a)
print("b:\n", b)

c = a + b
print("a + b:\n", c)


a:
 [[0 1 2]]
b:
 [[0]
 [1]
 [2]]
a + b:
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


In [21]:
# Example 2

In [20]:
a= np.arange(3).reshape(3)
b=np.arange(3).reshape(1,3)
print("a:\n", a)
print("b:\n", b)
c=a+b
print("c:\n",c)



a:
 [0 1 2]
b:
 [[0 1 2]]
c:
 [[0 2 4]]
