In [3]:
import numpy as np

In [ ]:
#Calculte the union among the two set
m = np.array([1,2,3,4,5,6])
n = np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n) #intersection

array([3, 4, 5, 6])

In [7]:
#set diff
np.setdiff1d(m,n)

array([1, 2])

In [8]:
#xor 
np.setxor1d(m,n)

array([1, 2, 7])

In [ ]:
np.in1d(m,1) #if condition matches it return true

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_33280\3930963099.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False, False])