In [1]:
import numpy as np

In [ ]:
# returns the position or index of the maximum element in an array

In [ ]:
a= np.random.randint(1,100,15)#1D array
a

array([12, 86, 10, 47, 89, 42, 19, 76, 93, 83, 93, 28, 54, 89, 36],
      dtype=int32)

In [3]:
np.argmax(a)

np.int64(8)

In [4]:
b=np.random.randint(1,100,24).reshape(6,4)#2D array
b

array([[70, 34, 69, 24],
       [50, 49, 38, 37],
       [81,  2, 46, 40],
       [57, 56, 46, 48],
       [65, 51, 88, 57],
       [25, 17, 52,  8]], dtype=int32)

In [5]:
np.argmax(b)

np.int64(18)

In [ ]:
# maximum element index position in row
np.argmax(b,axis=1)

array([0, 0, 0, 0, 2, 2])

In [8]:
# maximum element index position in col
np.argmax(b,axis=0)

array([2, 3, 4, 4])

In [9]:
#np.argmin
a

array([12, 86, 10, 47, 89, 42, 19, 76, 93, 83, 93, 28, 54, 89, 36],
      dtype=int32)

In [ ]:
np.argmin(a)#1 D array

np.int64(2)

In [ ]:
np.argmin(b)#2 D array

np.int64(9)

In [16]:
np.argmin(b,axis=1) # maximum element index position in row


array([3, 3, 1, 2, 1, 3])

In [15]:
np.argmin(b,axis=0) # maximum element index position in col


array([5, 2, 1, 5])