In [ ]:
import numpy as np
a= np.random.randint(1,100,15)
a

array([88, 91, 52, 41, 51,  6, 45,  1, 26, 33,  1, 61, 95,  2, 67],
      dtype=int32)

In [2]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([4, 0, 1, 1, 2, 2, 2, 0, 1, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [3]:
salary = np.array([20000,40000,250000,70000,60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[ 1.       , -0.0378964],
       [-0.0378964,  1.       ]])