In [1]:
import numpy as np
a= np.random.randint(1,100,15)
a

array([63, 32, 61,  6, 53, 39, 73, 35, 15, 14, 27, 25, 71, 64, 74],
      dtype=int32)

In [ ]:
#flip function is used to reverse the oder.

In [2]:
np.flip(a)

array([74, 64, 71, 25, 27, 14, 15, 35, 73, 39, 53,  6, 61, 32, 63],
      dtype=int32)

In [3]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[68, 47, 69, 25],
       [74, 77, 29, 94],
       [97, 30, 87, 52],
       [50, 49, 90,  9],
       [15, 29, 69, 21],
       [ 6,  2, 40, 18]], dtype=int32)

In [ ]:
np.flip(b,axis=0)#column flipped

array([[18, 40,  2,  6],
       [21, 69, 29, 15],
       [ 9, 90, 49, 50],
       [52, 87, 30, 97],
       [94, 29, 77, 74],
       [25, 69, 47, 68]], dtype=int32)

In [5]:
np.flip(b,axis=1)#row flipped

array([[25, 69, 47, 68],
       [94, 29, 77, 74],
       [52, 87, 30, 97],
       [ 9, 90, 49, 50],
       [21, 69, 29, 15],
       [18, 40,  2,  6]], dtype=int32)