In [ ]:
#Advance Indexing

In [1]:
#Normal Indexing and Slicing
import numpy as np
a= np.random.randint(1,100,24).reshape(6,4)

In [3]:
print(a[1,2])

29


In [4]:
a[1:3,1:3]

array([[48, 29],
       [56, 67]], dtype=int32)

In [8]:
#Fancing Indexing
a

array([[ 1, 74, 83, 90],
       [75, 82, 83, 80],
       [38, 12, 99, 65],
       [83, 49, 25, 37],
       [97, 69, 12, 33],
       [23,  8, 95, 15]], dtype=int32)

In [5]:
#Boolean Indexing
import numpy as np
a=np.random.randint(1,100,24).reshape(6,4)
a

array([[ 1, 74, 83, 90],
       [75, 82, 83, 80],
       [38, 12, 99, 65],
       [83, 49, 25, 37],
       [97, 69, 12, 33],
       [23,  8, 95, 15]], dtype=int32)

In [6]:
a[1:3,1:3]
a

array([[ 1, 74, 83, 90],
       [75, 82, 83, 80],
       [38, 12, 99, 65],
       [83, 49, 25, 37],
       [97, 69, 12, 33],
       [23,  8, 95, 15]], dtype=int32)

In [ ]:
#First Second and Third Column
a[:,[0,2,3]]

array([[ 1, 83, 90],
       [75, 83, 80],
       [38, 99, 65],
       [83, 25, 37],
       [97, 12, 33],
       [23, 95, 15]], dtype=int32)

In [ ]:
#Boolean Indexing
a= np.random.randint(1,100,24).reshape(6,4)

array([[42, 72, 68, 43],
       [93, 78, 40, 89],
       [ 9, 29, 48, 50],
       [35, 45, 37, 28],
       [40, 72, 26, 40],
       [78, 37, 81, 77]], dtype=int32)

In [12]:
#find all the number greater than 50
a>50

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True, False, False, False],
       [ True,  True, False, False],
       [False, False,  True, False]])

In [13]:
a[a>50] # geetting only those numbers number greater than 50

array([74, 83, 90, 75, 82, 83, 80, 99, 65, 83, 97, 69, 95], dtype=int32)

In [14]:
# find out even numbers
a%2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False,  True, False, False]])

In [16]:
a[a%2==0]

array([74, 90, 82, 80, 38, 12, 12,  8], dtype=int32)

In [17]:
#find all the number greater than 50 and are even.
a[(a>50)&(a%2==0)]

array([74, 90, 82, 80], dtype=int32)

In [19]:
#find all the number not divisible by 7
a[~(a%7==0)]

array([ 1, 74, 83, 90, 75, 82, 83, 80, 38, 12, 99, 65, 83, 25, 37, 97, 69,
       12, 33, 23,  8, 95, 15], dtype=int32)