In [1]:
import numpy as np
a= np.random.randint(1,100,15)
a

array([52, 31, 96, 73, 89, 92, 96, 34,  4, 64, 82, 81, 59, 15, 96],
      dtype=int32)

In [2]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[72, 29, 28,  6],
       [53, 93, 62, 49],
       [80, 54, 72, 42],
       [70, 72, 17, 39],
       [98, 68, 13, 89],
       [38, 83, 84, 58]], dtype=int32)

In [ ]:
#no. of items between two range just like a bar graph

In [3]:
a

array([52, 31, 96, 73, 89, 92, 96, 34,  4, 64, 82, 81, 59, 15, 96],
      dtype=int32)

In [4]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 0, 2, 0, 2, 1, 1, 3, 4]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [5]:
salary = np.array([20000,40000,250000,70000,60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[ 1.       , -0.0378964],
       [-0.0378964,  1.       ]])